# Generated by Django 3.2 on 2021-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTb',
            fields=[
                ('book_id', models.AutoField(db_column='BOOK_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BOOK_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentTb',
            fields=[
                ('content_id', models.AutoField(db_column='CONTENT_ID', primary_key=True, serialize=False)),
                ('sentence_id', models.IntegerField(db_column='SENTENCE_ID')),
                ('text', models.TextField(db_column='TEXT')),
                ('feelring', models.IntegerField(db_column='FEELRING')),
            ],
            options={
                'db_table': 'CONTENT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTb',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=30, primary_key=True, serialize=False)),
                ('pw', models.CharField(db_column='PW', max_length=30)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('e_mail', models.CharField(db_column='E_MAIL', max_length=50)),
            ],
            options={
                'db_table': 'USER_TB',
                'managed': False,
            },
        ),
    ]
